language: d
d:
  - dmd
  # - gdc
  # - llc

addons:
  apt:
    packages:
    - python3

install:
  - dub fetch doveralls
  - dub fetch trial --version=0.6.2

script:
  - dub run trial:runner -- :tests

after_failure:
  - cat tests.log
