language: d
d:
  - dmd
  # - gdc
  # - llc

addons:
  apt:
    packages:
    - libevent-dev
    - python3
    - python3-pip

install:
  - dub fetch doveralls
  - dub fetch trial --version=0.5.3

script:
  - dub run trial:runner -- :tests
